export default {
  // Navigation
  "nav.scroll": "Scroll",
  "nav.portfolio": "Yeeun Jo",
  "nav.home": "Home",
  "nav.work": "Work",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.otherProjects": "Other Projects",
  "nav.viewProject": "View Project",

  // TOC
  "toc.introduction": "Introduction",
  "toc.problem": "Problem",
  "toc.hypothesis": "Hypothesis",
  "toc.goToMarket": "Go-to-Market",
  "toc.approach": "Approach",
  "toc.behavioralModel": "Behavioral Model",
  "toc.limitations": "Limitations",
  "toc.insight": "Key Insights",
  "toc.references": "References",

  // Introduction
  "intro.tag": "Behavioral Design / Growth Experiment / App Concept",
  "intro.title": "Can Gamification Drive\nSustainable Digital Behavior?",
  "intro.desc": "A behavioral design experiment exploring how gamification can influence sustainable digital behavior. This is not just an app concept — it is a hypothesis-driven approach to understanding what actually drives people to act.",
  "intro.point1": "Behavioral design experiment",
  "intro.point2": "Hypothesis-driven approach",
  "intro.point3": "Focus on digital carbon footprint",

  // Problem
  "problem.title": "The Behavioral Problem",
  "problem.subtitle": "Users do not take action on reducing their digital carbon footprint because the impact feels invisible and unrewarding.",
  "problem.point1Title": "Invisible Impact",
  "problem.point1Desc": "Digital carbon footprint is abstract — users cannot see or feel the emissions generated by their data usage.",
  "problem.point2Title": "No Feedback Loop",
  "problem.point2Desc": "There is no immediate feedback that connects deleting data to any real-world environmental benefit.",
  "problem.point3Title": "No Personal Incentive",
  "problem.point3Desc": "Without visible reward or personal meaning, users lack motivation to change their digital habits.",

  // Hypothesis
  "hypothesis.title": "Hypothesis",
  "hypothesis.subtitle": "Making impact visible and rewarding can trigger sustained behavior change.",
  "hypothesis.step1Title": "Visibility",
  "hypothesis.step1Desc": "When users can see their data usage and its carbon cost, awareness is created.",
  "hypothesis.step2Title": "Reward",
  "hypothesis.step2Desc": "Points and donation impact provide emotional and structural motivation to act.",
  "hypothesis.step3Title": "Repetition",
  "hypothesis.step3Desc": "Progress tracking and badges reinforce the behavior until it becomes a habit.",

  // Go-to-Market
  "gtm.title": "Go-to-Market Consideration",
  "gtm.subtitle": "How to activate early adoption and create viral momentum for a behavioral change product.",
  "gtm.strategyTitle": "Launch Strategy",
  "gtm.strategyLabel": "Social-first growth loop",
  "gtm.desc": "To activate early adoption, this concept would rely on social challenges and shareable progress (e.g., #CleanYourPhoneChallenge) to create visibility and network effects.",
  "gtm.hashtag": "#CleanYourPhoneChallenge",
  "gtm.clickToCopy": "Click to copy hashtag",
  "gtm.copied": "Copied!",
  "gtm.imageAlt": "Social media challenge and network effects concept illustration",
  "gtm.tactic1Title": "Shareable Progress",
  "gtm.tactic1Desc": "Users share their cleanup results and badges, creating organic visibility across social platforms.",
  "gtm.tactic2Title": "Social Challenges",
  "gtm.tactic2Desc": "Group challenges drive peer pressure and collective action, turning individual cleanup into a community event.",
  "gtm.tactic3Title": "Network Effects",
  "gtm.tactic3Desc": "As more users join and share, the challenge gains credibility and attracts late adopters through social proof.",

  // Approach
  "approach.title": "Approach",
  "approach.subtitle": "A gamified system that connects digital cleanup actions to visible impact and rewards.",
  "approach.dataTitle": "Data Visibility",
  "approach.dataDesc": "Show users exactly how much data they use and its carbon equivalent.",
  "approach.actionTitle": "Cleanup Actions",
  "approach.actionDesc": "Guided, one-click deletion of unnecessary apps, emails, photos, and cache.",
  "approach.rewardTitle": "Reward System",
  "approach.rewardDesc": "Points for every cleanup action, redeemable as donations to environmental organizations.",
  "approach.progressTitle": "Progress Tracking",
  "approach.progressDesc": "Badges and streaks that visualize cumulative impact and sustain engagement.",

  // Behavioral Model
  "model.title": "Behavioral Loop",
  "model.subtitle": "Trigger → Action → Reward → Repeat",
  "model.triggerTitle": "Trigger",
  "model.triggerDesc": "Awareness of data usage and its hidden carbon cost creates the initial motivation.",
  "model.actionTitle": "Action",
  "model.actionDesc": "Deleting unnecessary data — a low-friction, one-click cleanup action.",
  "model.rewardTitle": "Reward",
  "model.rewardDesc": "Immediate points and visible donation impact provide emotional satisfaction.",
  "model.repeatTitle": "Repeat",
  "model.repeatDesc": "Progress tracking and badges create a feedback loop that encourages continued behavior.",

  // Limitations
  "limitations.title": "Limitations",
  "limitations.desc": "This project was not validated through real user testing. The behavioral impact remains a hypothesis. While the logic is grounded in behavioral science, actual engagement and long-term habit formation would require testing with real users.",

  // Key Insights
  "insight.title": "Key Insights",
  "insight.i1Title": "Visible Impact Drives Action",
  "insight.i1Desc": "Users act when impact becomes visible and personally meaningful. Abstract problems do not motivate behavior change.",
  "insight.i2Title": "Emotion + Structure Required",
  "insight.i2Desc": "Behavior change requires both emotional reward and structural feedback. One without the other is insufficient.",
  "insight.i3Title": "Visibility Creates Collective Behavior",
  "insight.i3Desc": "Individual actions feel insignificant, but visibility can drive collective behavior by making personal impact part of a larger story.",

  // App Solution (kept for phone mockups)
  "app.title": "App Concept",
  "app.subtitle": "A gamified interface connecting data cleanup to environmental impact.",
  "app.step1": "Check which apps use the most data and earn points instantly.",
  "app.step2": "Review data usage by category — photos, messages, apps.",
  "app.step3": "Delete data with one click and accumulate points.",
  "app.step4": "See your total saved data and current participation rate.",
  "app.step5": "Donate collected points to Greenpeace or other organizations.",
  "app.step6": "Receive confirmation and share your impact with others.",
  "app.step7": "Browse and select from multiple environmental organizations.",
  "app.step8": "Earn Carbon Neutral badges based on your achievements.",

  // References
  "ref.title": "References",
  "ref.source1": "Examining charitable giving in real-world online donations — Nature",
  "ref.source2": "Carbon Footprint of Data Centers & Data Storage Per Country (Calculator) — 8 Billion Trees",

  // Other Projects
  "other.karrot": "Karrot Campus Sprint",
  "other.anua": "Anua Consumer Behavior Report",
  "other.lg": "LG Interbrand Top 100 Strategy",
};